# The OPCUA connection parameters. If you want to use anonymous auth, 
# remove the username and password lines.
[opcua]
url             = "opc.tcp://172.27.172.27:4840"
user            = "eoshwi"
pass            = "Zhtl3QHDS5HMxwWwCHHz"

# The InfluxDB connection parameters. Use a connection url containing all 
# details, ie. http(s)://user:password@host:port/database
[influx]
url              = "http://admin:admin@10.118.143.102:8086/kepdb2"
writeInterval    = 1000          # optional. defaults to 1000ms
writeMaxPoints   = 1000          # optional. defaults to 1000 points

# For each metrics you want to collect, add a [[metrics]] object.
   
# Energy
[[metrics]]
measurement        = "Channel1.Device1.Tag1"
datatype           = "number"
tags               = { simulation = "false", location = "SI3976" }
nodeId             = "ns=2;s=Channel1.Device1.Tag1"
method             = "monitored"
interval           = 5000
